on:
  push:
    branches:
    - fr
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0
    - name: Build Docker Image
      run: docker build . -t ${{ secrets.DOCKERU }}/ryuu-play:latest
    - name: Push Docker Image
      run: docker login -u ${{ secrets.DOCKERU }} -p ${{ secrets.DOCKERP }} && docker push ${{ secrets.DOCKERU }}/ryuu-play:latest
